### ISSUE TITLE
Drift

### ISSUE THREAD

**Issue by dcanelhas** [victorprad/InfiniTAM#10]
Experiment:
- Start InfiniTAM
- Reconstruct small environment, 
- Place camera on table, pointed at static part of scene,
- Wait for a couple of minutes;
- Use f to see the scene from a different viewpoint

Expected result: 
slight surface degradation due to quantization and continuous integration without motion
Actual result: 
![drift](https://cloud.githubusercontent.com/assets/2123506/5186759/c0a59824-74c8-11e4-8d52-65ab484aaa89.jpg)

Possible reasons why it happens:
- There is some offset somewhere in the image alignment (maybe a missing +0.5 on a pixel coordinate somewhere)?
- The TSDF values are not being returned correctly
- Factory calibration is not enough?

**Comment by dcanelhas** [comment]
Not sure if anything has changed in to address this issue specifically, but it doesn't appear to be happening in the current version so I will close this issue.

**Comment by lyxLeo-0728** [comment]
Hello, I have encountered the same problem. My problem is that the disparity parameters in calib.txt has not been replaced with a new sensor after the Azure kinect DK has been replaced.  hope it can help you
