### ISSUE TITLE
Compile problem in Ubuntu

### ISSUE THREAD

**Issue by root29** [victorprad/InfiniTAM#103]
[  1%] Building NVCC (Device) object ITMLib/CMakeFiles/ITMLib.dir/ITMLib_generated_CUDAInstantiations.cu.o
/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00001487_00000000-7_CUDAInstantiations.cpp1.ii".
CMake Error at ITMLib_generated_CUDAInstantiations.cu.o.cmake:266 (message):
  Error generating file
  /home/cy/InfiniTAM-master/InfiniTAM/build/ITMLib/CMakeFiles/ITMLib.dir//./ITMLib_generated_CUDAInstantiations.cu.o

ITMLib/CMakeFiles/ITMLib.dir/build.make:1001: recipe for target 'ITMLib/CMakeFiles/ITMLib.dir/ITMLib_generated_CUDAInstantiations.cu.o' failed
make[2]: *** [ITMLib/CMakeFiles/ITMLib.dir/ITMLib_generated_CUDAInstantiations.cu.o] Error 1
CMakeFiles/Makefile2:334: recipe for target 'ITMLib/CMakeFiles/ITMLib.dir/all' failed
make[1]: *** [ITMLib/CMakeFiles/ITMLib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Please help me ,Thanks!

**Comment by sgolodetz** [comment]
Does this help?

https://github.com/NVIDIA/nccl/issues/29

**Comment by root29** [comment]
Thanks for your reply!
I‘m trying to solve the problem, but I should add cxx flag into makefile? I'm not good at cmake, sorry!
 @sgolodetz

**Comment by sgolodetz** [comment]
You can put them in Flags.cmake.
