### ISSUE TITLE
Infinitam_V3 on IOS

### ISSUE THREAD

**Issue by CrazyHUAN** [victorprad/InfiniTAM#109]
Hi,

I repaired the code error By Apps/iOS in the master branch, It was compiled successfully on the Simulators. But when I switch to the Iphone X,

**/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include/sys/cdefs.h:763:2: Unsupported architecture**
 
![image](https://user-images.githubusercontent.com/15259562/44652091-9972a100-aa1d-11e8-8375-e35838b7eb4b.png)

 /Users/jokeszhou/Desktop/InfiniTAM/src/InfiniTAM/InfiniTAM/ITMLib/Engines/Visualisation/Metal/ITMVisualisationEngine.metal:7:10: In file included from /Users/jokeszhou/Desktop/InfiniTAM/src/InfiniTAM/InfiniTAM/ITMLib/Engines/Visualisation/Metal/ITMVisualisationEngine.metal:7:

 /Users/jokeszhou/Desktop/InfiniTAM/src/InfiniTAM/InfiniTAM/ITMLib/Engines/Visualisation/Shared/ITMVisualisationEngine_Shared.h:5:10: In file included from /Users/jokeszhou/Desktop/InfiniTAM/src/InfiniTAM/InfiniTAM/ITMLib/Engines/Visualisation/Metal/../Shared/ITMVisualisationEngine_Shared.h:5:

 /Users/jokeszhou/Desktop/InfiniTAM/src/InfiniTAM/InfiniTAM/ITMLib/Objects/Scene/ITMRepresentationAccess.h:5:10: In file included from /Users/jokeszhou/Desktop/InfiniTAM/src/InfiniTAM/InfiniTAM/ITMLib/Engines/Visualisation/Metal/../Shared/../../../Objects/Scene/ITMRepresentationAccess.h:5:

 /Users/jokeszhou/Desktop/InfiniTAM/src/InfiniTAM/InfiniTAM/ITMLib/Objects/Scene/ITMVoxelBlockHash.h:13:10: In file included from /Users/jokeszhou/Desktop/InfiniTAM/src/InfiniTAM/InfiniTAM/ITMLib/Engines/Visualisation/Metal/../Shared/../../../Objects/Scene/ITMVoxelBlockHash.h:13:

/Users/jokeszhou/Desktop/InfiniTAM/src/InfiniTAM/InfiniTAM/ORUtils/MemoryBlockPersister.h:10:10: In file included from /Users/jokeszhou/Desktop/InfiniTAM/src/InfiniTAM/InfiniTAM/ITMLib/Engines/Visualisation/Metal/../Shared/../../../Objects/Scene/../../../ORUtils/MemoryBlockPersister.h:10:

/Users/jokeszhou/Desktop/InfiniTAM/src/InfiniTAM/InfiniTAM/ORUtils/Image.h:6:10: In file included from /Users/jokeszhou/Desktop/InfiniTAM/src/InfiniTAM/InfiniTAM/ITMLib/Engines/Visualisation/Metal/../Shared/../../../Objects/Scene/../../Utils/../../ORUtils/Image.h:6:

/Users/jokeszhou/Desktop/InfiniTAM/src/InfiniTAM/InfiniTAM/ORUtils/Vector.h:5:10: In file included from /Users/jokeszhou/Desktop/InfiniTAM/src/InfiniTAM/InfiniTAM/ITMLib/Engines/Visualisation/Metal/../Shared/../../../Objects/Scene/../../Utils/../../ORUtils/Vector.h:5:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include/math.h:30:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include/math.h:30:

I asked for help on stackoverflow, but I did not solve this problem,so I want to know if you are suitable for V3 in IOS?

The following is my modified file:
[ios-fixPatch.zip](https://github.com/victorprad/InfiniTAM/files/2323250/ios-fixPatch.zip)

Thank you for any kind of help!

**Comment by CrazyHUAN** [comment]
this is due to the call to the C++ header file in Metel.
Close the issue

**Comment by wxyz-lang** [comment]
Do you have make it success to run v3 on ios? @CrazyHUAN
