### ISSUE TITLE
Add reading jpeg files and shaded with color to InfiniTAM

### ISSUE THREAD

**Issue by AIBluefisher** [victorprad/InfiniTAM#117]
Hi, @sgolodetz 
I add a function to read the jpeg files and shaded with color to InfiniTAM, now it can read the NUIM dataset and bundle fusion dataset. Below is the effect of Living_Room dataset of NUIM
![_001](https://user-images.githubusercontent.com/18096136/47137427-15d08480-d2e9-11e8-9607-ba35329c3803.png)

If it's necessary to make a pull request?

**Comment by nonlinear1** [comment]
could give share your code with all of infintam lovers?
