### ISSUE TITLE
What's the coordinate of Infinitam pose?

### ISSUE THREAD

**Issue by zzxxtt** [victorprad/InfiniTAM#119]
Hello, Thank you for your project. When I want to change the pose of Infinitam from tracker to my given pose, I found that the coordinate of tracker -> pose_d is quiet strange. I think the coordinate is right-hand coordinate and z to front, y to down, x to right. The pose is world to camera pose. I change different trackers and it all about the same.

When I move the camera to front for about 0.1m the translation of pose_d changes for three axis, the values are about x - 0.1, y - 0.1, z + 0.1. When I move the camera down for about 0.1m, translation of pose_d changes for y axis for double, x,z nearly the same, y + 0.2. When the camera move to right about 0.1m, its seems right, x + 0.1m.

Could you help me solve the problem, thank you?

**Comment by sgolodetz** [comment]
The InfiniTAM camera pose is indeed X right, Y down, Z forwards, and world to camera. As far as I know, the underlying reason for this was to correspond to the way in which image coordinates are generally X right, Y down.

What problem are you experiencing exactly? Is it that the change in pose doesn't seem to correspond to the way in which you're moving the camera? From what you're saying, it doesn't sound obviously wrong - are you sure you're not just moving it slightly off-axis? From personal experience, it's hard to e.g. move a camera precisely along the z axis without introducing some x-y movement as well.
