### ISSUE TITLE
Problems about FileBasedTracker

### ISSUE THREAD

**Issue by morgenzhang** [victorprad/InfiniTAM#120]
Hi,
I want to apply InfiniTAM to do 3D mapping on KITTI odometry dataset. I have pre-computed the depth map of each frame and also want to use the ground truth poses as input. I find that you have already provided such tracker named ITMFileBasedTracker. So I changed the trackerConfig in ITMLibSetting to:
trackerConfig = "type=file, mask=/path/to/gt_pose/sequencenum/%04i.txt";
I also added some script to see if each pose has been readed correctly:

processing one frame (0)...
Loading odometry ground truth from file: /home/zhangyic/Downloads/Semantic_Mapping/kitti_data/gt_pose/01/0000.txt
Current pose in file based tracker:
1, 0, 0, 0
0, 1, 0, 0
0, 0, 1, 0
0, 0, 0, 1

processing one frame (1)...
Loading odometry ground truth from file: /home/zhangyic/Downloads/Semantic_Mapping/kitti_data/gt_pose/01/0001.txt
Current pose in file based tracker:
0.99905, -0.00165, 0.043552, 0.051547
0.00176, 0.999995, -0.002502, -0.024249
-0.043548, 0.002577, 0.999048, 1.00073
0, 0, 0, 1
...
However, when I started the InfiniTAM, and selected by default "follow camera", the output view can not display any result (as shown below)
![screenshot from 2018-11-16 15-22-53](https://user-images.githubusercontent.com/38669666/48627659-66ed9a00-e9b5-11e8-8b50-ba77a2493255.png)
If I typed f and change to free view mode, I can somehow see the result (as shown below)
![screenshot from 2018-11-16 15-37-04](https://user-images.githubusercontent.com/38669666/48627791-c64baa00-e9b5-11e8-97f9-f7566117b013.png)

Can you explain why this happened? Or whether I have made some mistakes when using this filebasedtracker? If so, I hope you can give me some instruction on how to use it. Thank you very much for your time.

**Comment by HuanyuanZhou** [comment]
Hi, I meet the same problem. Could you tell me how you solve this problem?
