### ISSUE TITLE
NVCC fatal compile error even with cuda 10.0

### ISSUE THREAD

**Issue by sabrinazuraimi** [victorprad/InfiniTAM#122]
Hi, I tried to build the Cmake files but I ran into the following error

> [ 28%] Building NVCC (Device) object ITMLib/CMakeFiles/ITMLib.dir/Trackers/CUDA/ITMLib_generated_ITMExtendedTracker_CUDA.cu.o
> nvcc fatal   : Unsupported gpu architecture 'compute_61'
> CMake Error at ITMLib_generated_ITMExtendedTracker_CUDA.cu.o.cmake:222 (message):
>   Error generating
>   /home/muser/Desktop/InfiniTAM-master/build/ITMLib/CMakeFiles/ITMLib.dir/Trackers/CUDA/./ITMLib_generated_ITMExtendedTracker_CUDA.cu.o
> 
> 
> ITMLib/CMakeFiles/ITMLib.dir/build.make:105: recipe for target 'ITMLib/CMakeFiles/ITMLib.dir/Trackers/CUDA/ITMLib_generated_ITMExtendedTracker_CUDA.cu.o' failed
> make[2]: *** [ITMLib/CMakeFiles/ITMLib.dir/Trackers/CUDA/ITMLib_generated_ITMExtendedTracker_CUDA.cu.o] Error 1
> CMakeFiles/Makefile2:334: recipe for target 'ITMLib/CMakeFiles/ITMLib.dir/all' failed
> make[1]: *** [ITMLib/CMakeFiles/ITMLib.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2

I do have cuda 10.0 and cudnn version 7(verified below), which shoud work fine with compute_61??

Typing nvcc --version returns

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```
and   cat /usr/local/cuda-10.0/include/cudnn.h | grep CUDNN_MAJOR -A 2 returns

```
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 4
#define CUDNN_PATCHLEVEL 1
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"

```

**Comment by sabrinazuraimi** [comment]
Sorry, I think I figured out why, my cuda is located in /usr/local/cuda-10.0 and editing the cmake files to that path fixed the compute_61 error

**Comment by Richard-coder** [comment]
I have the same problem as you. Can you tell me how you solved it?
