### ISSUE TITLE
Is there a method to provide camera pose?

### ISSUE THREAD

**Issue by Myzhar** [victorprad/InfiniTAM#131]
I would like to provide the camera pose using my own algorithm. 
Is there a method?

**Comment by sgolodetz** [comment]
Yes, add a subclass of ITMTracker and plumb it in.

**Comment by Myzhar** [comment]
Solved subclassing ITMTracker. I close the issue

**Comment by rcffc** [comment]
@Myzhar Would you mind sharing your custom tracker with me? My Email is peter.jiang@igd.fraunhofer.de
