### ISSUE TITLE
Can't Save mesh GPU

### ISSUE THREAD

**Issue by wangyuanbiubiubiu** [victorprad/InfiniTAM#141]
When I try to save the result on the GPU, I report this error
`cudaSafeCall() Runtime API error : out of memory.`
How do I solve this，Thanks！

**Comment by sgolodetz** [comment]
Specify a smaller maximum number of triangles, e.g. see the Application::save_mesh() function here: https://github.com/torrvision/spaint/blob/master/apps/spaintgui/Application.cpp

**Comment by sgolodetz** [comment]
(Or upgrade your GPU to a bigger one :))

**Comment by sgolodetz** [comment]
In the InfiniTAM code, you need to search for where the ITMMesh is being created and pass in the maximum number of triangles you want there.

**Comment by wangyuanbiubiubiu** [comment]
Thank you!Its right.
