### ISSUE TITLE
compiled without support

### ISSUE THREAD

**Issue by fang-lai** [victorprad/InfiniTAM#144]
initialising ...
using calibration file: 
trying OpenNI device: <OpenNI default device> - calibration: internal
Calibration filename not specified. Using default parameters.
compiled without OpenNI support
trying UVC device
Calibration filename not specified. Using default parameters.
compiled without LibUVC support
trying RealSense device
Calibration filename not specified. Using default parameters.
compiled without RealSense Windows support
trying RealSense device with SDK 2.X (librealsense2)
Calibration filename not specified. Using default parameters.
compiled without RealSense SDK 2.X support
trying MS Kinect 2 device
Calibration filename not specified. Using default parameters.
compiled without Kinect 2 support
trying PMD PicoFlexx device
Calibration filename not specified. Using default parameters.
compiled without LibRoyale support
failed to open any image stream

thinks

**Comment by fang-lai** [comment]
OPTION(WITH_OPENNI "Build with OpenNI support?" OFF)

**Comment by calmelo** [comment]
What the OPTION mean? It's not legal arguments and I can't understand.

**Comment by sgolodetz** [comment]
@calmelo It's a CMake option - when you configure with CMake, you can set it to enable/disable building with OpenNI support.
