### ISSUE TITLE
Show nothing when running InfiniTAM.exe with files in Teddy

### ISSUE THREAD

**Issue by HanzhiC** [victorprad/InfiniTAM#149]
Hello!

After successfully compling InfiniTAM without any problems (I assume), I try to run the InfiniTAM.exe to see how it works, but the display frame is all black and shows nothing even if I am very show that I am giving the right path to the data. Could you please kindly provide some suggestions on how to solve this issue?

I try to execute the following command in cmd:

I:\InfiniTAM\InfiniTAM\build\Apps\InfiniTAM\Release\InfiniTAM.exe I:\InfiniTAM\InfiniTAM\Teddy\calib.txt I:\InfiniTAM\InfiniTAM\Teddy\Frames\ %04i.ppm I:\InfiniTAM\InfiniTAM\Teddy\Frames\ %04i.pgm

But it gives the following display, really understand which step of my installation might be wrong.
![image](https://user-images.githubusercontent.com/47291733/84344780-38aa5d80-abde-11ea-96c7-b0d59346508b.png)

**Some information**
System: Windows 10
Version: InfiniTAM v3
3rd party: freeglut 3.0.0 (I did not install OpenNI, CUDA and other optional stuff)
Compliler: VS 2019

Thanks!

**Comment by sgolodetz** [comment]
Have you tried pressing B or N?

**Comment by HanzhiC** [comment]
> Have you tried pressing B or N?

Yes

**Comment by HanzhiC** [comment]
Now I work out, It seemes to be my input method problem! Thanks!

**Comment by tftangming** [comment]
Hello, I met the smame problem, what is your input method problem???

**Comment by HanzhiC** [comment]
> Hello, I met the smame problem, what is your input method problem???

switch to English if you are using other languages
