### ISSUE TITLE
How big is the voxel grid?

### ISSUE THREAD

**Issue by Dennis199607** [victorprad/InfiniTAM#152]
Hi to everyone!

I am not sure about something in InfiniTAM since I am pretty new to this program. The voxels are saved inside Voxel Blocks each one containing 512 voxels (8x8x8 Voxels). But how big is the grid consisting of the voxel blocks (how many voxel blocks in x,y and z direction?). Or does the grid consisting of the Voxel Blocks have dynamic boundaries since it is for large scale reconstruction?

My problem is that I need to build an Octree. All i have to do is to transform the coordinates from the Octree nodes (x,y and z ranging from 0 to 1) to the coordinates of the Voxels in InfiniTAM.

**Comment by MaxHeimbrock** [comment]
Hello, 
the voxel grid is infinite in theory, it dynamically allocates new voxel blocks, as long as you have space in your hash table. The size of the hash table is defined in  [InfiniTAM/InfiniTAM/ITMLib/Objects/Scene/ITMVoxelBlockHash.h](https://github.com/victorprad/InfiniTAM/blob/master/InfiniTAM/ITMLib/Objects/Scene/ITMVoxelBlockHash.h).
