### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by rcffc** [victorprad/InfiniTAM#154]
Has anyone tried to code a Python wrapper around this? Would it be feasible?

**Comment by sgolodetz** [comment]
Yes, I've tried it with pybind - totally feasible. It's not fully tidy yet, but I can share what I've got so far if it's helpful.

**Comment by rcffc** [comment]
Sure, I would love to see it!

**Comment by sgolodetz** [comment]
Ok, I've added you to the repo. Note that it depends on `spaint` as well, since some of the stuff I needed is in that, but make what you will of it I guess :) Note also that you need to be on the `pynfinitam` branch of InfiniTAM, since I had to tweak a few things in the main code to get it to work.

**Comment by rcffc** [comment]
Thanks a lot!

**Comment by 4ri4Slr** [comment]
@sgolodetz Would you mind adding me to the repo as well?

**Comment by sgolodetz** [comment]
@4ri4Slr Done!
