### ISSUE TITLE
C1083	Cannot open include file: 'GL/glut.h': No such file or directory

### ISSUE THREAD

**Issue by rcffc** [victorprad/InfiniTAM#156]
I use freeglut 3.0.0 from https://www.transmissionzero.co.uk/software/freeglut-devel/ .
Then I use CMake to configure and generate.
However, when I want to build the project in VS, I get the error in the title. In Project -> Linker -> Input, the path to C:\Program Files\freeglut-MSVC-3.0.0-2.mp\freeglut\lib\x64\freeglutd.lib is included.

I have also tried to use freeglut built from source, but to no avail :/

**Comment by sgolodetz** [comment]
Not sure what the specific problem you have is off the top of my head, but this might help:

https://github.com/victorprad/InfiniTAM/blob/infinitam_v3.5/build-win.sh

Maybe try getting the .zip file specified in there and see if that one works.

**Comment by sgolodetz** [comment]
Also this might be handy:

https://github.com/victorprad/InfiniTAM/blob/infinitam_v3.5/cmake/UseGLUT.cmake

**Comment by rcffc** [comment]
> 
> 
> Not sure what the specific problem you have is off the top of my head, but this might help:
> 
> https://github.com/victorprad/InfiniTAM/blob/infinitam_v3.5/build-win.sh
> 
> Maybe try getting the .zip file specified in there and see if that one works.

Sadly I am getting the same error with this version.

**Comment by sgolodetz** [comment]
So the error you're getting is a compiler error, not a linker error - you need to set the include directories appropriately, it's not a problem with the linker input. If you switch to the `infinitam_v3.5` branch, the `build-win.sh` build script will set things up properly for you (you need to install Git Bash). Failing which, check the include directories, and make sure that `GL/glut.h` can be found from one of them.

**Comment by rcffc** [comment]
I fixed it: My problem was pointing the include library 
of freeglut to `include/GL` instead of `include` in cmake GUI.
Thanks for your support!
