### ISSUE TITLE
Issues when using ASUS Xtion on Windows

### ISSUE THREAD

**Issue by connerbrooks** [victorprad/InfiniTAM#19]
When using the Xtion sensor the application starts and OpenNI initializes the device correctly. When integration begins, a few frames get processed and then the application hangs and becomes unresponsive. When using the Kinect 1 with OpenNI there is no repro of this bug on Windows. When we tested the Xtion on Ubuntu it works as expected.

Tested on Windows 8 and 10 with VS 2013.
Using OpenNI2 binary installer.

**Comment by ManuelK89** [comment]
Hmm I also use the Xtion Pro Live on Windows with VS 2013 (both Windows 7 and Windows 8.1) and it runs without any problems. Do you know at which point in the code it stops working?

**Comment by connerbrooks** [comment]
Unfortunately I cannot find the exact point as the application just becomes unresponsive after processing a few frames. I tried having OpenNI request 320 x 240 instead of 640 x 480 and now it can run without issues, but that doesn't really solve the problem.

I have tried to debug with WinDBG and some tools from NVIDIA but when the app hangs the tools have issues as well.

To get more specific I'm using a GTX 970.

**Comment by victorprad** [comment]
I had the same problem at some point and this seemed to work:

http://com.occipital.openni.s3.amazonaws.com/Structure%20Sensor%20OpenNI2%20Quick%20Start%20Guide.pdf

**Comment by connerbrooks** [comment]
@victorprad of course! I'll give that a try, totally forgot about those docs.

**Comment by connerbrooks** [comment]
Docs added.
