### ISSUE TITLE
Teddy/Frames/%04i.ppm Teddy/Frames/%04i.pgm

### ISSUE THREAD

**Issue by LiliMeng** [victorprad/InfiniTAM#27]
Thanks a lot for the code!

What kind of files 04i.ppm and 04i.pgm are? As I put some rgb images(changed name to 1c.png, 2c.png...) and depth images(changed name to 1d.png, 2d.png...) in the Teddy folder from TUM RGBD dataset, it displayed: 
initialising ...
using calibration file: Teddy/calib.txt
using rgb images: Teddy/1c.png
using depth images: Teddy/1d.png
error reading file 'Teddy/1c.png'
error reading file 'Teddy/1d.png'

Thanks a lot!

**Comment by Thunderbolt-sx** [comment]
ppm and pgm are "raw" image file for color and gray image respectively. You should not simply rename it for format conversion, it will not work. Use tools like imagemagick if you really want to convert between different format.

**Comment by LiliMeng** [comment]
Thanks a lot! Using the matlab functions it could convert many png to ppm/pgm very efficiently
for i = 1 :100
 I = imread(sprintf('%d.png', i));
 imwrite(I, sprintf('%d.ppm', i));
end

**Comment by Thunderbolt-sx** [comment]
Are you sure you start depth images with 111.pgm? Could you please check if the images actually exist at the specified path? If everything fails, try to download data I have just uploaded [here](https://drive.google.com/file/d/0B1nzrhyFOuT3RVNkcEtIOUtUUHM/view?usp=sharing)

**Comment by LiliMeng** [comment]
Thanks a lot @Thunderbolt-sx  ! Your Teddy dataset works really great!( https://www.youtube.com/watch?v=XPsw8efq6eU). It's a little bit wired by using the rgbd_dataset_freiburg2_large_with_loop from (http://vision.in.tum.de/data/datasets/rgbd-dataset/download). And the original png format rgb photos are converted to ppm format, the png format depth photos are converted to pgm format by using matlab tool(https://github.com/LiliMeng/matlabForComputerVisionTools/blob/master/fromPNGtoPPM.m).  The video for RGBDdataset is here(https://www.youtube.com/watch?v=mXt8AYPDwq4)

What's wrong with this RGBDdataset testing? Is that because too few depth information? 

Thanks again!

**Comment by Thunderbolt-sx** [comment]
The depth format is obviously wrong. We use either "raw" depth data with calibration, or short depth in mm unit.

**Comment by connerbrooks** [comment]
> The depth images are scaled by a factor of 5000, i.e., a pixel value of 5000 in the depth image corresponds to a distance of 1 meter from the camera, 10000 to 2 meter distance, etc. A pixel value of 0 means missing value/no data.

[TUM file format descriptions](https://vision.in.tum.de/data/datasets/rgbd-dataset/file_formats)

You have to covert to the format that InfiniTAM expects.

**Comment by LiliMeng** [comment]
@connerbrooks  Thanks a lot! How to convert the format? thanks again!:)

**Comment by connerbrooks** [comment]
I'm not entirely sure, I am trying to work that out.

**Comment by drinkingcoder** [comment]
Can I find the ppm and pgm files to implement the video demo anywhere? It's so strange that the folder 'Teddy' contains only a calib file without frames data.

**Comment by sgolodetz** [comment]
@drinkingcoder: See the download page here:

http://www.robots.ox.ac.uk/~victor/infinitam/download.html

In particular, the link is:

http://www.robots.ox.ac.uk/~victor/infinitam/files/teddy_20141003.zip

The reason it's not in the repository is because it's big, and not everyone needs it.

**Comment by drinkingcoder** [comment]
@sgolodetz :Get it. Thanks!

**Comment by xiaoyaozhuzi** [comment]
mark

**Comment by renhaofan** [comment]
> Are you sure you start depth images with 111.pgm? Could you please check if the images actually exist at the specified path? If everything fails, try to download data I have just uploaded [here](https://drive.google.com/file/d/0B1nzrhyFOuT3RVNkcEtIOUtUUHM/view?usp=sharing)

Thanks again

**Comment by jizhu1023** [comment]
mark
