### ISSUE TITLE
ASUS Xtion for the Input

### ISSUE THREAD

**Issue by LiliMeng** [victorprad/InfiniTAM#28]
Hi,
      Thanks a lot for the great InfiniTAM code!
      Could it also use ASUS Xtion as input sensor? Thanks a lot!

**Comment by sgolodetz** [comment]
@LiliMeng: The ASUS Xtion works well with InfiniTAM.

**Comment by LiliMeng** [comment]
Thanks a lot @sgolodetz ! How to start/launch the ASUS Xtion in this case? previously it was launched in ROS rviz using roslaunch openni_launch openni.launch.

Thanks again!

**Comment by sgolodetz** [comment]
@LiliMeng: What stage are you at with setting it up? Have you got the OpenNI2 sample programs up and running with the ASUS?

**Comment by walklinzhang** [comment]
Did you solve this problem , I need help too.
