### ISSUE TITLE
Poor framerate

### ISSUE THREAD

**Issue by arennuit** [victorprad/InfiniTAM#37]
Hello,

I am using InfiniTAM with a Asus Xtion Pro (using OpenNI2) and currently no calibration file on Ubuntu 14.04. I have a serious laptop (i7 latest generation) with a serious GPU (GTX 970M - high end for notebooks).

When testing InfiniTAM I am a bit surprised of the framerate I obtain (I would say about 0.5 to 5 frames/s most of the time + freezes every now and then + smooth every now and them). Obviously with such a framerate the tracking and SLAM is very bad.

I am a bit surprised to get this behaviour and low framerate. Any idea of where it could come from?

Also I have checked the framerate I obtain when I run a plain OpenNI2 sample (NiViewer) and it runs very smooth.

Any idea of how to investigate this issue? I am not even sure where to start...

Regards,

Antoine.

**Comment by sgolodetz** [comment]
Two thoughts:

* Try updating the firmware on your Asus.
* Decrease the resolution of your RGB input to 320x240.

I encountered similar issues with the Asus (particularly on Windows) and those two steps helped a lot.

**Comment by arennuit** [comment]
Thanks a lot @sgolodetz, it does the trick ;)

Though I am not sure I understand why, as I thought RGB data was not used in the default ITMLibSettings.

Also, because of this, can you confirm the calib files only contain the registration between the RGB and D sensors and nothing else?

Regards,

Antoine.

**Comment by sgolodetz** [comment]
I didn't write the calib file bit - best ask @olafkaehler.

**Comment by arennuit** [comment]
Understood! Thanks for your relevant help ;)

**Comment by olafkaehler** [comment]
Our OpenNI interfacing class still opens both RGB and depth streams by default. The RGB images are not used in the default configuration, and we should probably not request RGB images unless we actually do use colour. The USB-bandwidth problems only appears to occur with certain system configurations, though, I've encountered them on Linux so far.

The calibration files also contain the intrinsic calibration parameters of the depth and RGB cameras. You'll probably get marginally better results if you calibrate your own camera, but in practice it doesn't make a big difference.

**Comment by arennuit** [comment]
Hello @olafkaehler, I see your point for the RGB stream access. My problem did occur on Ubuntu 14.04 and was solved using @sgolodetz's trick.

For the calibration do you mean that:
1. because I only use the D sensor, the extrinsinc parameters won't be very useful?
2. because the intrinsic parameters don't vary much, the calibration will be of limited impact?

**Comment by olafkaehler** [comment]
You are exactly right about the calibration in both points.

**Comment by arennuit** [comment]
Got it, thanks!
