### ISSUE TITLE
Teddy example crashes when using Nvidia Quadro K420 with 1GB memory

### ISSUE THREAD

**Issue by hling** [victorprad/InfiniTAM#42]
When I compile InfiniTAM with CPU setting on Ubuntu Linux 14.04, I can successfully run the Teddy example. However, when I compile it with CUDA 7.5 and run it with an Nvidia Quadro K420 card (with 1GB memory) on the same machine, the program crashes with an out of memory error as follows:
InfiniTAM/ITMLib/Engine/../Utils/../Objects/../../ORUtils/MemoryBlock.h(217) : cudaSafeCall() Runtime API error : out of memory.

Has anyone else seen the same problem? Do you have any suggestion to resolve it? I am pretty sure my CUDA drive is installed correctly. I successfully ran all the NVIDIA_CUDA-7.5 Samples and saw the GPU version gains significant speedup compared to the CPU version on all sample programs.

BTW, I use  ./InfiniTAM Teddy/calib.txt Teddy/Frames/%04i.ppm Teddy/Frames/%04i.pgm command to run the Teddy example.

Thanks!

**Comment by sgolodetz** [comment]
You could try changing the settings in `ITMVoxelBlockHash.h` - if it's just a case of it running out of memory then decreasing the number of stored blocks should help.

**Comment by hling** [comment]
Stuart, thanks for your quick response. Yes, it is working now after changing the parameters that are set in ../Utils/ITMLibDefines.h.

**Comment by sgolodetz** [comment]
Glad that helped (and sorry for the wrong file reference - I was looking at the latest internal branch rather than the public one).
