### ISSUE TITLE
Bug in RealSense wrapper?

### ISSUE THREAD

**Issue by jmaye** [victorprad/InfiniTAM#48]
I found out that this line of code should be added in RealSenseEngine.cpp:

this->calib.disparityCalib.params = Vector2f(data->dev->get_depth_scale(), 0.0f);

Otherwise, it seems to work nicely with that, thanks a lot to the contributors.

P.S.: sorry not to go through the github pull requests mechanism, I'm a bit in a rush:)

**Comment by olafkaehler** [comment]
Great! I was wondering whether there is a function for this but obviously didn't read the API documentation very well... :)

Should be fixed now in the master branch!

**Comment by jmaye** [comment]
Perfect! Thanks for your work!
