### ISSUE TITLE
How to generate a project which can work on the iPad with Metal?

### ISSUE THREAD

**Issue by Liuyangdong** [victorprad/InfiniTAM#49]
I have successfully used InfiniTAM framework on the iPad to reconstruct the indoor scenes with Structure Sensor capturing the depth information. But the project I'v generated only using the CPU and it takes about 100ms to process one frame. 

The question is how to generate a project which can work on the iPad with Metal?
Thanks!

**Comment by victorprad** [comment]
You need a few defines in the project to use the Metal version. You can download a demo Xcode project from http://www.robots.ox.ac.uk/~victor/infinitam/files/InfiniTAM_ios9.zip . If you want to build that you need to add the Structure.framework from http://structure.io to the Frameworks folder.

**Comment by Liuyangdong** [comment]
Thank you very much for your patient reply, and I will have a try!
