### ISSUE TITLE
Problems about learning the code

### ISSUE THREAD

**Issue by MarkZurkberg** [victorprad/InfiniTAM#51]
I have compiled InfiniTAM-spaint_v2, and I am trying to understand the code nowadays. Due to so many complex source files I found it's difficult to learn, although I have generate doxygen files it seems not useful for my learning process. Can somebody tell me how to learn the code and master the core algorithm? Thanks!

**Comment by sgolodetz** [comment]
The main pipeline is in `ITMBasicEngine<...>::ProcessFrame`. I would start from there and drill down, trying to figure out how things correspond to the descriptions in the various papers as I go.

An understanding of the way in which the CPU/GPU code is structured is also probably useful - basically you have an interface class, CPU and CUDA classes that derive from it, and shared code that is called by the implementations of the various member functions in the CPU and CUDA classes.

**Comment by MarkZurkberg** [comment]
These days I tried to use GLM to load .obj models into scene generated by InfiniTAM, but it didn't work yet. Every time I use function glmReadOBJ to load, nothing has happened and the reconstruction scene is always the same. I wonder where I should put the code to make it work. Thanks! @sgolodetz

**Comment by MarkZurkberg** [comment]
I have used glm to load a 3D object successfully, but I don't know how to integrate this with InfiniTAM so now it is just limited in its own window. I want to find the entry point for the reconstruction scene so that I can add some furnitures into InfiniTAM. Could you please give me some advice? Thanks! @sgolodetz

**Comment by MarkZurkberg** [comment]
I have used glm to load a 3D object successfully, but I don't know how to integrate this with InfiniTAM so now it is just limited in its own window. I want to find the entry point for the reconstruction scene so that I can add some furnitures into InfiniTAM. Could you please give me some advice? Thanks! @sgolodetz 

![Uploading infiniTAM.gif…]()

**Comment by MarkZurkberg** [comment]
I have used glm to load a 3D object successfully, but I don't know how to integrate this with InfiniTAM so now it is just limited in its own window. I want to find the entry point for the reconstruction scene so that I can add some furnitures into InfiniTAM. Could you please give me some advice? Thanks! @sgolodetz

**Comment by sgolodetz** [comment]
Depending on the format of the object, this may be more or less tricky - but in terms of adding things to the scene, the best places to look in the code are probably the bits to do with the scene representation (drill down from `ITMScene`) and the scene reconstruction engine (drill down from `ITMSceneReconstructionEngine`).
