### ISSUE TITLE
Build error...

### ISSUE THREAD

**Issue by amiltonwong** [victorprad/InfiniTAM#6]
Dear all,

I had followed the install step but came across the following build error:
(It seems the linking to openni2 issue but I had built openni2 successfully before)
# 

[ 96%] Built target Engine
Scanning dependencies of target InfiniTAM
[100%] Building CXX object CMakeFiles/InfiniTAM.dir/InfiniTAM.cpp.o
Linking CXX executable InfiniTAM
Engine/libEngine.a(OpenNIEngine.cpp.o): In function `openni::OpenNI::waitForAnyStream(openni::VideoStream**, int, int*, int) [clone .constprop.32]':
OpenNIEngine.cpp:(.text+0x1e5): undefined reference to`oniWaitForAnyStream'
Engine/libEngine.a(OpenNIEngine.cpp.o): In function `InfiniTAM::Engine::OpenNIEngine::getImages(ITMLib::Objects::ITMView*)':
OpenNIEngine.cpp:(.text+0x38c): undefined reference to`oniStreamReadFrame'
OpenNIEngine.cpp:(.text+0x3a2): undefined reference to `oniFrameRelease'
OpenNIEngine.cpp:(.text+0x3d4): undefined reference to`oniStreamReadFrame'
OpenNIEngine.cpp:(.text+0x3ea): undefined reference to `oniFrameRelease'
Engine/libEngine.a(OpenNIEngine.cpp.o): In function`InfiniTAM::Engine::OpenNIEngine::OpenNIEngine(char const_, char const_, bool, ITMLib::Vector2<int>, ITMLib::Vector2<int>)':
OpenNIEngine.cpp:(.text+0x883): undefined reference to `oniInitialize'
OpenNIEngine.cpp:(.text+0x888): undefined reference to`oniGetExtendedError'
OpenNIEngine.cpp:(.text+0x8ef): undefined reference to `oniDeviceSetProperty'
OpenNIEngine.cpp:(.text+0x91e): undefined reference to`oniDeviceSetProperty'
OpenNIEngine.cpp:(.text+0x951): undefined reference to `oniDeviceSetProperty'
OpenNIEngine.cpp:(.text+0x96c): undefined reference to`oniDeviceCreateStream'
OpenNIEngine.cpp:(.text+0x979): undefined reference to `oniGetExtendedError'
OpenNIEngine.cpp:(.text+0x9b3): undefined reference to`oniDeviceCreateStream'
OpenNIEngine.cpp:(.text+0x9c0): undefined reference to `oniGetExtendedError'
OpenNIEngine.cpp:(.text+0x9ff): undefined reference to`oniShutdown'
OpenNIEngine.cpp:(.text+0xa79): undefined reference to `oniStreamGetSensorInfo'
OpenNIEngine.cpp:(.text+0xad6): undefined reference to`oniStreamIsPropertySupported'
OpenNIEngine.cpp:(.text+0xaf1): undefined reference to `oniStreamIsPropertySupported'
OpenNIEngine.cpp:(.text+0xcae): undefined reference to`oniStreamSetProperty'
OpenNIEngine.cpp:(.text+0xcea): undefined reference to `oniStreamSetProperty'
OpenNIEngine.cpp:(.text+0xd07): undefined reference to`oniStreamStart'
OpenNIEngine.cpp:(.text+0xda9): undefined reference to `oniDeviceOpen'
OpenNIEngine.cpp:(.text+0xdb6): undefined reference to`oniGetExtendedError'
OpenNIEngine.cpp:(.text+0xe39): undefined reference to `oniStreamGetSensorInfo'
OpenNIEngine.cpp:(.text+0xe96): undefined reference to`oniStreamIsPropertySupported'
OpenNIEngine.cpp:(.text+0xeb1): undefined reference to `oniStreamIsPropertySupported'
OpenNIEngine.cpp:(.text+0x1075): undefined reference to`oniStreamSetProperty'
OpenNIEngine.cpp:(.text+0x10b7): undefined reference to `oniStreamSetProperty'
OpenNIEngine.cpp:(.text+0x10d4): undefined reference to`oniStreamStart'
OpenNIEngine.cpp:(.text+0x116a): undefined reference to `oniDeviceGetSensorInfo'
OpenNIEngine.cpp:(.text+0x11da): undefined reference to`oniDeviceGetSensorInfo'
OpenNIEngine.cpp:(.text+0x1251): undefined reference to `oniGetExtendedError'
OpenNIEngine.cpp:(.text+0x12e9): undefined reference to`oniGetExtendedError'
OpenNIEngine.cpp:(.text+0x1364): undefined reference to `oniStreamDestroy'
OpenNIEngine.cpp:(.text+0x1374): undefined reference to`oniStreamDestroy'
OpenNIEngine.cpp:(.text+0x16f7): undefined reference to `oniDeviceGetInfo'
OpenNIEngine.cpp:(.text+0x1705): undefined reference to`oniDeviceIsPropertySupported'
OpenNIEngine.cpp:(.text+0x171c): undefined reference to `oniDeviceIsPropertySupported'
OpenNIEngine.cpp:(.text+0x1733): undefined reference to`oniDeviceIsCommandSupported'
OpenNIEngine.cpp:(.text+0x1763): undefined reference to `oniDeviceIsPropertySupported'
OpenNIEngine.cpp:(.text+0x1901): undefined reference to`oniDeviceIsPropertySupported'
OpenNIEngine.cpp:(.text+0x1918): undefined reference to `oniDeviceIsCommandSupported'
Engine/libEngine.a(OpenNIEngine.cpp.o): In function`InfiniTAM::Engine::OpenNIEngine::~OpenNIEngine()':
OpenNIEngine.cpp:(.text+0x1976): undefined reference to `oniStreamStop'
OpenNIEngine.cpp:(.text+0x19ea): undefined reference to`oniStreamStop'
OpenNIEngine.cpp:(.text+0x1ab6): undefined reference to `oniFrameRelease'
OpenNIEngine.cpp:(.text+0x1ad2): undefined reference to`oniFrameRelease'
OpenNIEngine.cpp:(.text+0x1c84): undefined reference to `oniShutdown'
OpenNIEngine.cpp:(.text+0x1ca4): undefined reference to`oniStreamDestroy'
OpenNIEngine.cpp:(.text+0x1cb4): undefined reference to `oniStreamDestroy'
OpenNIEngine.cpp:(.text+0x1cc1): undefined reference to`oniDeviceClose'
OpenNIEngine.cpp:(.text+0x1cd4): undefined reference to `oniStreamDestroy'
OpenNIEngine.cpp:(.text+0x1ce4): undefined reference to`oniDeviceClose'
OpenNIEngine.cpp:(.text+0x1cf4): undefined reference to `oniStreamDestroy'
OpenNIEngine.cpp:(.text+0x1d77): undefined reference to`oniFrameRelease'
Engine/libEngine.a(OpenNIEngine.cpp.o): In function `openni::VideoStream::~VideoStream()':
OpenNIEngine.cpp:(.text._ZN6openni11VideoStreamD2Ev[_ZN6openni11VideoStreamD5Ev]+0x74): undefined reference to`oniStreamDestroy'
Engine/libEngine.a(OpenNIEngine.cpp.o): In function `openni::Device::~Device()':
OpenNIEngine.cpp:(.text._ZN6openni6DeviceD2Ev[_ZN6openni6DeviceD5Ev]+0xa4): undefined reference to`oniDeviceClose'
collect2: ld returned 1 exit status
make[2]: **\* [InfiniTAM] Error 1
make[1]: **\* [CMakeFiles/InfiniTAM.dir/all] Error 2
make: **\* [all] Error 2
# 

Could someone give me suggestions to fix it?

Best regards,
Milton

**Comment by LiliMeng** [comment]
how to remove openNI1 ?Thanks a lot!

**Comment by LiliMeng** [comment]
just change the CMakeLists.txt 
find_package(OpenNI QUIET)  to find_package(OpenNI2 QUIET)
