### ISSUE TITLE
after build how to install project ?  

### ISSUE THREAD

**Issue by HamdiBenAbdallah** [victorprad/InfiniTAM#61]
Please how to run project ?

![capture](https://cloud.githubusercontent.com/assets/25033063/22405718/3d6908b8-e647-11e6-9a14-4c3c959021b5.PNG)

**Comment by sgolodetz** [comment]
@HamdiBenAbdallah: Press 'B'. Assuming you've got a suitable camera attached, that will start capturing frames and fusing the data into the map.

**Comment by HamdiBenAbdallah** [comment]
Thank you for your response. It's working, but how to save the 3D model plz?

**Comment by HamdiBenAbdallah** [comment]
Thank you very much !!!
best regards
