### ISSUE TITLE
successful build but how to run infinTAM in visual studio ?

### ISSUE THREAD

**Issue by HamdiBenAbdallah** [victorprad/InfiniTAM#63]
Hi, Please how to run infinTAM in visual studio not with file .exe in C:\InfiniTAM\InfiniTAM\build\Release ?

**Comment by sgolodetz** [comment]
Right-click on the InfiniTAM project (not the solution), click Set as StartUp Project, then go to the Debug menu and select Start Without Debugging.

**Comment by HamdiBenAbdallah** [comment]
Very good. 
thank you so much !!!! 
Very kind
best regards.
