### ISSUE TITLE
Is infiniTAMv3 now compatible with SemanticPaint?

### ISSUE THREAD

**Issue by jawhster** [victorprad/InfiniTAM#76]
I noticed that about a month ago, spaint_v3 branch is eqivalent to infiniTAM master (which is v3). Therefore, is infiniTAMv3 now compatible with SemanticPaint? I have infiniTAMv3 working but am receiving the following errors when building SemanticPaint solution after successful CMake. I wonder if this is occurring because of my folder structure. I have the folders currently setup as follows:

Root
Root / InfiniTAM-master
Root / InfiniTAM-master / InfiniTAM
Root / spaint-master

Error	1	error C2039: 'afHost' : is not a member of 'af'	C:\Users\wilson\Desktop\04AustonProject\spaint-master\tests\scratch\arrayfire\main.cpp	47	1	scratchtest_arrayfire
Error	2	error C1083: Cannot open include file: 'ITMLib/Objects/ITMScene.h': No such file or directory	c:\users\wilson\desktop\04austonproject\spaint-master\modules\spaint\include\spaint\features\interface\FeatureCalculator.h	11	1	spaint
Error	3	error C1083: Cannot open include file: 'ITMLib/ITMLib.h': No such file or directory	C:\Users\wilson\Desktop\04AustonProject\spaint-master\tests\scratch\infinitam\main.cpp	1	1	scratchtest_infinitam
Error	8	error C1083: Cannot open include file: 'ITMLib/Engine/DeviceSpecific/CUDA/ITMRenTracker_CUDA.cu': No such file or directory	C:\Users\wilson\Desktop\04AustonProject\spaint-master\apps\spaintgui\CUDAInstantiations.cu	6	1	spaintgui
Error	10	error C2664: 'void std::_Tree<std::_Tmap_traits<_Kty,_Ty,_Pr,_Alloc,false>>::insert(std::initializer_list<std::pair<const _Kty,_Ty>>)' : cannot convert argument 1 from 'std::pair<const void *,boost::shared_ptr<const rafl::Example<Label>>>' to 'std::pair<const _Kty,_Ty> &&'	C:\local\boost_1_56_0\boost\serialization\shared_ptr_helper.hpp	182	1	raflvis
Error	11	error LNK1104: cannot open file '..\..\lib\spaint_d.lib'	C:\Users\wilson\Desktop\04AustonProject\spaint-master\build\apps\touchtrain\LINK	touchtrain

Thanks,
Justin

**Comment by sgolodetz** [comment]
Which branch of SemanticPaint are you building? If you build the `spaint_v3` branch (which hasn't been officially released, but is actually public on GitHub, it should build fine against InfiniTAM v3). I might need to update the readme though. Let me know how you get on and I can fix things up.

**Comment by jawhster** [comment]
Thank you Stuart! I built the SemanticPaint **master** branch. I didn't notice spaint_v3 until after building SemanticPaint master with infiniTAMv3 and debugging the errors. I'll try building spaint_v3 tomorrow and let you know. In addition to these, I was also getting identification errors (e.g. ovrHmd undefined) when using newer version of Oculus SDK but unchecked in CMake to remove that option for now. I was also getting a BLAS not found in CMake so modified the make file to find Intel MKL instead. Just mentioning as you update the readme =D

When are you planning to officially release with an updated readme? Thanks so much

**Comment by sgolodetz** [comment]
Newer versions of the Oculus SDK aren't currently supported unfortunately - I don't have time to update it at the moment, but I might one day if I get a moment. For now, if you use the version specified in the readme, it should work (let me know if you can't get hold of it - I can send it your way). Interesting about BLAS - in what context were you getting that error?

I probably won't get a chance to update the readme till later in September - this week's a bit hectic because of the impending ICRA deadline, and then I'm away for a week.

**Comment by jawhster** [comment]
Great, thanks for the update! I'll see what I can do and can always use infiniTAMv2 until then if I need to. Best on the deadline and your week away.

**Comment by jawhster** [comment]
Hi Stuart - I'm trying to build spaintv3. Could you please send me Oculus 0.5.0.1 SDK (unless spaintv3 uses a different version as this is from the spaintv2 readme)? I don't think versions before 0.8 are available online anymore. Thanks a lot, Justin

**Comment by sgolodetz** [comment]
@jawhster: Sure, I'm just sending them across on WeTransfer (they're quite big).

**Comment by jawhster** [comment]
Thanks, I received the SDK files. Any idea how to solve error "Error	1	error C1083: Cannot open include file: 'opencv2/aruco.hpp': No such file or directory	C:\Users\wilson\Desktop\04AustonProject\ROOTv3\spaint\modules\spaint\src\fiducials\ArUcoFiducialDetector.cpp	13	1	spaint"

**Comment by jawhster** [comment]
Nevermind. I think that I need to rebuild open cv with the additional contributing modules to get aruco. I'll look into more tomorrow. Thanks

**Comment by jawhster** [comment]
For now, I disabled OpenCV and reconfigured. Looks like only remaining error is the following, which is preventing spaint to build and generate spaint_d.lib. Any ideas how to resolve this one? Thanks so much 

Error	2	error C2664: 'void std::_Tree<std::_Tmap_traits<_Kty,_Ty,_Pr,_Alloc,false>>::insert(std::initializer_list<std::pair<const _Kty,_Ty>>)' : cannot convert argument 1 from 'std::pair<const void *,boost::shared_ptr<const rafl::Example<Label>>>' to 'std::pair<const _Kty,_Ty> &&'	C:\local\boost_1_56_0\boost\serialization\shared_ptr_helper.hpp	186	1	spaint

**Comment by sgolodetz** [comment]
@jawhster: If I remember correctly, there's a bug in one of the Boost headers in version 1.56.0. In my Boost build script (`build-boost_1_56_0-win.sh`), I have a line that says:

    perl -ibak -pe 's/SPT<void>/SPT<const void>/g' ../boost_1_56_0/include/boost/serialization/shared_ptr_helper.hpp

You probably haven't picked up the fix if you didn't build SemanticPaint using the build script (the `C:\local` path you have suggests this might be the case).

**Comment by sgolodetz** [comment]
And yes, you need to build OpenCV with the contributor modules. The `build-opencv-3.1.0-win.sh` build script in the `libraries` subdirectory should set everything up for you correctly, but please let me know if it doesn't.

**Comment by jawhster** [comment]
I followed below lines in README and the build completes but no main application in <root>/build/bin/apps/spaintgui/spaintgui. I also pasted output from running ./build-win.sh 12 Release. I still receive boost related error too when rebuild the .sln even after build-boost was run. Thanks

1.3.1 Build Process (Windows)
  f) Using a Bash shell (e.g. Git Bash, provided with msysgit), run the top-level build script, e.g. for VS2013:
    $ ./build-win.sh 12 Release
  g) Run the CMake GUI and specify <root>/spaint/build as the build directory.
  h) Enable any optional libraries you want and supply the paths.
  i) Reconfigure and regenerate the Visual Studio solution.
  j) Build with the optional libraries enabled (just run the above build command again).

$ ./build-win.sh 12 Release
[spaint] Building Boost 1.56.0 for msvc-12.0
[spaint] ...Extracting archive...
[spaint] ...Bootstrapping...
[spaint] ...Running build...
[spaint] ...Fixing headers...
[spaint] ...Finished building Boost 1.56.0.
[spaint] Building glew 1.12.0
[spaint] ...Skipping archive extraction (already extracted)
[spaint] ...Running build...
[spaint] ...Finished building glew-1.12.0.
[spaint] Building LodePNG 20160501 for Visual Studio 12 Win64
[spaint] ...Extracting archive...
[spaint] ...Configuring using CMake...

$ ./build-win.sh 12 Release
[spaint] Building Boost 1.56.0 for msvc-12.0
[spaint] ...Skipping build (already built)
[spaint] Building glew 1.12.0
[spaint] ...Skipping archive extraction (already extracted)
[spaint] ...Running build...
[spaint] ...Finished building glew-1.12.0.
[spaint] Building LodePNG 20160501 for Visual Studio 12 Win64
[spaint] ...Skipping archive extraction (already extracted)
[spaint] ...Skipping build (already built)
[spaint] ...Finished building LodePNG 20160501.
[spaint] Building SDL 2.0.3 for Visual Studio 12 Win64
[spaint] ...Extracting archive...
[spaint] ...Configuring using CMake...

$ ./build-win.sh 12 Release
[spaint] Building Boost 1.56.0 for msvc-12.0
[spaint] ...Skipping build (already built)
[spaint] Building glew 1.12.0
[spaint] ...Skipping archive extraction (already extracted)
[spaint] ...Running build...
[spaint] ...Finished building glew-1.12.0.
[spaint] Building LodePNG 20160501 for Visual Studio 12 Win64
[spaint] ...Skipping archive extraction (already extracted)
[spaint] ...Skipping build (already built)
[spaint] ...Finished building LodePNG 20160501.
[spaint] Building SDL 2.0.3 for Visual Studio 12 Win64
[spaint] ...Skipping archive extraction (already extracted)
[spaint] ...Skipping build (already built)
[spaint] ...Installing...

**Comment by sgolodetz** [comment]
In CMake, where does it think your Boost directory is? If you haven't changed it after building Boost with the script, it might still be using your version in `C:\local`.

**Comment by jawhster** [comment]
I deleted CMake cache and works now. 41 projects succeeded and just 2 left that fail. Thanks so much for the help. Errors now are:

Error	4	error LNK2019: unresolved external symbol main referenced in function __tmainCRTStartup	C:\Users\wilson\Desktop\04AustonProject\ROOTv3\spaint\build\tests\scratch\sdl\MSVCRTD.lib(crtexe.obj)	scratchtest_sdl

Error	5	error LNK1120: 1 unresolved externals	C:\Users\wilson\Desktop\04AustonProject\ROOTv3\spaint\build\bin\tests\scratch\scratchtest_sdl\scratchtest_sdl.exe	scratchtest_sdl

Error	12	error LNK2019: unresolved external symbol "class boost::unit_test::test_suite * __cdecl init_unit_test_suite(int,char * * const)" (?init_unit_test_suite@@YAPEAVtest_suite@unit_test@boost@@HQEAPEAD@Z) referenced in function main	C:\Users\wilson\Desktop\04AustonProject\ROOTv3\spaint\build\apps\spaintgui\libboost_unit_test_framework-mt-gd.lib(unit_test_main.obj)	spaintgui

Error	13	error LNK1120: 1 unresolved externals	C:\Users\wilson\Desktop\04AustonProject\ROOTv3\spaint\build\bin\apps\spaintgui\spaintgui.exe	1	1	spaintgui

**Comment by jawhster** [comment]
I fixed 1 out of 2. Solved the _tmainCRTStartup error using this [StackOverflow post](https://stackoverflow.com/questions/4845410/error-lnk2019-unresolved-external-symbol-main-referenced-in-function-tmainc). Still stuck on the below error:

Error	1	error LNK2019: unresolved external symbol "int __cdecl test_main(int,char * * const)" (?test_main@@YAHHQEAPEAD@Z) referenced in function "public: void __cdecl test_main_caller::operator()(void)" (??Rtest_main_caller@@QEAAXXZ)	C:\Users\wilson\Desktop\04AustonProject\ROOTv3\spaint\build\apps\spaintgui\test_main.obj	spaintgui
Error	2	error LNK1120: 1 unresolved externals	C:\Users\wilson\Desktop\04AustonProject\ROOTv3\spaint\build\bin\apps\spaintgui\spaintgui.exe	1	1	spaintgui

**Comment by sgolodetz** [comment]
@jawhster: I wonder if it's related to something like this: https://github.com/Microsoft/vcpkg/issues/352?

**Comment by sgolodetz** [comment]
Can you check if `spaintgui` has `BOOST_ALL_NO_LIB` defined? (It's in `UseBoost.cmake`, so it should do.) I'm wondering if it's doing something like trying to auto-link Boost.Test, and encountering problems because SDL is already replacing `main`. See also: https://www.npcglib.org/~stathis/blog/2012/05/25/coding-tip-disable-autolinking-in-boost/

**Comment by jawhster** [comment]
Thanks for your reply. I know you have a deadline coming up so reply when you are available (no rush). Yes, BOOST_ALL_NO_LIB is defined in UseBoost.cmake and I added output messages around the definition statement to make sure that definition is being executed when configuring and generating with CMake GUI. I also checked that the definition is available in Visual Studio spaintgui project properties (see screenshot attached). Based on the other link you shared, it says "It sounds like both the boost test monitor and SDL2main.lib need to be moved into the manual-link directory" but I'm not sure how to do that. Thanks, Justin

![error_boost_all_no_lib](https://user-images.githubusercontent.com/10354137/30281664-0142d594-96e1-11e7-9414-ae0474a45a8d.png)

**Comment by raffienficiaud** [comment]
I wrote a piece of documentation for using `boost.test` through `cmake`: http://www.boost.org/doc/libs/1_65_1/libs/test/doc/html/boost_test/section_faq.html#boost_test.section_faq.how_to_set_up_a_cmake_project_us

I believe in your setup either boost.test shared/static libraries are not declared for inclusion by the linker (if this is shared/static library, see usage variants http://www.boost.org/doc/libs/1_65_1/libs/test/doc/html/boost_test/usage_variants.html). If this is a header only inclusion of `boost.test`, then I believe the boost user mailing list is the place to discuss.

Cheers

**Comment by jawhster** [comment]
I just added #include <boost/test/unit_test.hpp> after #define BOOST_TEST_MAIN and it worked. Then I was receiving a “Error MSB3073” setlocal error because I had different CMake variables set for glut directory and glut root so was having problems making a copy from one to the other. I made the variables all point to the same directory which fixed that error. Finally, when trying to run the spaintgui.exe after **a successful build**, I was receiving errors cudart64_80.dll, cublas64_80.dll, cufft64_80.dll, and cusparse64_80.dll missing which looks like CUDA 8 is required but I set CMake to CUDA v7. I'm installing CUDA v8 now and will rebuild. Thanks for all the help.

**Comment by sgolodetz** [comment]
Delete both the include and the define - they're making spaintgui into a test application and shouldn't be present.

**Comment by sgolodetz** [comment]
If the define was there before, that also explains the previous linker error I think.

**Comment by jawhster** [comment]
I commented out the define and include but again receive below error:

Error	1	error LNK2019: unresolved external symbol "class boost::unit_test::test_suite * __cdecl init_unit_test_suite(int,char * * const)" (?init_unit_test_suite@@YAPEAVtest_suite@unit_test@boost@@HQEAPEAD@Z) referenced in function main	C:\Users\wilson\Desktop\04AustonProject\ROOTv3\spaint\build\apps\spaintgui\libboost_unit_test_framework-mt-gd.lib(unit_test_main.obj)	spaintgui

**Comment by sgolodetz** [comment]
Hmm. So `init_unit_test_suite` is indeed referenced in a file called `unit_test_main.ipp` in Boost. The relevant code is surrounded by:

    #if !defined(BOOST_TEST_DYN_LINK) && !defined(BOOST_TEST_NO_MAIN)

As a result, I wonder if you might get some mileage out of defining `BOOST_TEST_NO_MAIN`, which will prevent Boost.Test from trying to redefine `main`. I'm not sure why it's necessary, if that is the issue - I thought you had to define `BOOST_TEST_MAIN` to ask it to do that, and I have no issues with it my end - but it's worth a try.

The behaviour you're experiencing as a result of including the header (that it links) makes sense - that's including the definition of `init_unit_test_suite`, as needed if you're picking up the `main` from `unit_test_main.ipp`.

**Comment by jawhster** [comment]
First, I mistakenly had a semicolon instead of colon in my value for SDLMAIN_LIBRARY which was creating a C.lib library include and causing an error. Next, I incorrectly had SDLMAIN_LIBRARY pointing to SDL2.lib instead of SDL2main.lib. After fixing this in CMake, reconfiguring, regenerating, and rebuilding, works great! Thanks,

SDLMAIN_LIBRARY:FILEPATH=C;/Users/wilson/Desktop/04AustonProject/SDL2-2.0.3/lib/x64/SDL2.lib

This should be pointing at SDL2main.lib. SDL replaces the main function, so if linking in the wrong library that explains the problem.
