### ISSUE TITLE
Cmake freezes PC under Windows 7

### ISSUE THREAD

**Issue by WASCHMASCHINE** [victorprad/InfiniTAM#77]
While configuring in Cmake with "Visual Studio 14 Win 64" the PC freezes during cuda_compute_capability.c. CUDA 8.0 is installed. On another PC it seems to be working fine, any ideas?

**Comment by sgolodetz** [comment]
What happens if you build and run the program as a standalone executable?

**Comment by AndreiBarsan** [comment]
A full PC freeze seems like a CUDA/driver issue to me. Are you able to compile and run other CUDA programs OK? (E.g., the CUDA samples.)

**Comment by WASCHMASCHINE** [comment]
Yep, my CUDA went berserk. Oh geez...
