### ISSUE TITLE
"Test setup error: test tree is empty" when running spaintgui.exe

### ISSUE THREAD

**Issue by jawhster** [victorprad/InfiniTAM#79]
I'm using infiniTAMv3 and spaint_v3 branch. I was just able to get successful build of all the projects after issue help from https://github.com/victorprad/InfiniTAM/issues/76. Below is output when I try to run spaintgui from Visual Studio.

**Error part of output**
First-chance exception at 0x00007FFC15A23C58 in spaintgui.exe: Microsoft C++ exception: boost::unit_test::framework::setup_error at memory location 0x000000ED454FF828.
The thread 0x238c has exited with code 200 (0xc8).
The thread 0x2f18 has exited with code 200 (0xc8).
The thread 0xb10 has exited with code 200 (0xc8).
The program '[10564] spaintgui.exe' has exited with code 200 (0xc8)

**Full Output**
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
'spaintgui.exe' (Win32): Loaded 'C:\Users\wilson\Desktop\04AustonProject\ROOTv3\spaint\build\bin\apps\spaintgui\spaintgui.exe'. Symbols loaded.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Users\wilson\Desktop\04AustonProject\ROOTv3\spaint\build\bin\apps\spaintgui\SDL2.dll'. Module was built without symbols.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Users\wilson\Desktop\04AustonProject\ROOTv3\spaint\build\bin\apps\spaintgui\glew32.dll'. Module was built without symbols.
'spaintgui.exe' (Win32): Loaded 'C:\Users\wilson\Desktop\04AustonProject\ROOTv3\spaint\build\bin\apps\spaintgui\freeglut.dll'. Module was built without symbols.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\glu32.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\opengl32.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Users\wilson\Desktop\04AustonProject\ROOTv3\spaint\build\bin\apps\spaintgui\OpenNI2.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\msvcp120d.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\msvcr120d.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\vcomp120d.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Program Files\ArrayFire\v3\lib\afcuda.dll'. Symbols loaded.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\ddraw.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\msvcr100.dll'. Symbols loaded.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cudart64_80.dll'. Module was built without symbols.
'spaintgui.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cublas64_80.dll'. Module was built without symbols.
'spaintgui.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cusparse64_80.dll'. Module was built without symbols.
'spaintgui.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvrtc64_80.dll'. Module was built without symbols.
'spaintgui.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cusolver64_80.dll'. Module was built without symbols.
'spaintgui.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cufft64_80.dll'. Module was built without symbols.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\dciman32.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\nvcuda.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\setupapi.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\vcomp140.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
'spaintgui.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\dbghelp.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Windows\System32\nvfatbinaryLoader.dll'. Cannot find or open the PDB file.
'spaintgui.exe' (Win32): Loaded 'C:\Program Files\ArrayFire\v3\lib\forge.dll'. Cannot find or open the PDB file.
First-chance exception at 0x00007FFC15A23C58 in spaintgui.exe: Microsoft C++ exception: boost::unit_test::framework::setup_error at memory location 0x000000ED454FF828.
The thread 0x238c has exited with code 200 (0xc8).
The thread 0x2f18 has exited with code 200 (0xc8).
The thread 0xb10 has exited with code 200 (0xc8).
The program '[10564] spaintgui.exe' has exited with code 200 (0xc8).

**Comment by sgolodetz** [comment]
This doesn't sound too surprising - spaintgui isn't supposed to be a test application, it's a normal application. As a result, it doesn't contain any tests. Your changes made it into a test application - when you try to run it, it then says it doesn't have any tests, which makes sense.
