### ISSUE TITLE
Integration of stereo sensors

### ISSUE THREAD

**Issue by WASCHMASCHINE** [victorprad/InfiniTAM#80]
I fiddled around with the code and I am on the edge between just implementing a TSDF + rendering by myself or using InfiniTAM. I am using one RGB image and one float depth image as my input (e.g. KITTI dataset), which was computed by a stereo pair of cameras.

Let's say I want to integrate InfiniTAM into my existing project. 
1) How should I change the depth map representation format in InfiniTAM? I think it is a short image, not float image. So I am losing resolution.
2) Can I disable the tracking and use my own?

**Comment by sgolodetz** [comment]
Regarding (1), take a look at what `ITMViewBuilder` does - internally, it converts the short image to a float image to store in the `ITMView`. As a result, if you have a float image to start with, it shouldn't be too tricky to quickly write an alternative version of `UpdateView` that takes that and stores it in the `ITMView` instead.

Regarding (2), yes - just override `ITMTracker` with your own tracker class and instantiate one of those instead. See this line in `ITMBasicEngine`:

    tracker = ITMTrackerFactory::Instance().Make(imgSize_rgb, imgSize_d, settings, lowLevelEngine, imuCalibrator, scene->sceneParams);

**Comment by WASCHMASCHINE** [comment]
Thank you, Stuart. You are very helpful! :)
