### ISSUE TITLE
infinitam v3 fails to save mesh with w option

### ISSUE THREAD

**Issue by shomedas** [victorprad/InfiniTAM#81]
I compiled infinitam with openni2 support on ubuntu 14.04,64 bit with nvidia gtx 760(4GB RAM)
I ran build/Apps/InfiniTAM/InfiniTAM. When I tried to save mesh by pressing w, I get error:

saving scene to model ... /home/shome/softwares/infinitam_v3/InfiniTAM/InfiniTAM/ITMLib/Objects/Scene/../../../ORUtils/MemoryBlock.h(257) : cudaSafeCall() Runtime API error : out of memory.

Do I need a better gpu?

**Comment by sgolodetz** [comment]
You can specify a maximum number of triangles when constructing the mesh object - that might save enough GPU memory to allow it to work.

**Comment by sgolodetz** [comment]
Search for 'new ITMMesh' and you'll likely find where it's being constructed.

**Comment by shomedas** [comment]
tried it with titan x. works fine now.
