### ISSUE TITLE
warping in room scan

### ISSUE THREAD

**Issue by shomedas** [victorprad/InfiniTAM#82]
I tried to scan my lab room using carmine 1.09 and titanx . I saved the mesh using w. When i opended the mesh.stl, I found that the walls appeared to be warped. The angle between adjacent walls appears to be less than 90 degree. In reality it is 90 degree. Also long walls appear curved, when the end of the wall is far from the sensor. The zipped mesh.stl is attached herewith. The effect was more pronounced with carmine 1.09(short range) than with carmine 1.08(long range)
[mesh.stl.zip](https://github.com/victorprad/InfiniTAM/files/1325180/mesh.stl.zip)

**Comment by sgolodetz** [comment]
Try turning on loop closure (see Olaf's paper "Real-time Large-Scale Dense 3D Reconstruction with Loop Closure" for the difference this makes) and ensure your sensor is properly calibrated (e.g. see appendix C.2 in https://arxiv.org/pdf/1702.04405.pdf). The combination of those two things should help quite a bit.
