### ISSUE TITLE
the result is abnormal when using saved rgb and depth images

### ISSUE THREAD

**Issue by ThePetrelLHY** [victorprad/InfiniTAM#85]
I can run InfiniTAMv2 with kinectv1 successfully. 
![_20171024153933](https://user-images.githubusercontent.com/13608731/31930226-98a81950-b8d1-11e7-8a66-99c4db1cc253.png)

The result is normal and i saved the rgb and depth images by tap key's' when running. 

But when I used the saved images to run InfiniTAMv2, the result is abnormal and I noticed that the depth image is not like the depth image reading from kinectv1 directly.
![_20171024153911](https://user-images.githubusercontent.com/13608731/31930231-9c8b5442-b8d1-11e7-829b-ba5c5a457c55.png)

Is there anything wrong or do i need to change some parameter to save the depth images?

**Comment by AndreiBarsan** [comment]
Hmm, the flat areas in the depth buffer visualization seem to point to a possible calibration issue. Are you able to run other pre-recorded sequences (like teddy) OK? What calibration parameters are you using at the moment?

**Comment by ThePetrelLHY** [comment]
Yeah, I can run the teddy ok...
![image](https://user-images.githubusercontent.com/13608731/31977133-fbba7d5c-b96d-11e7-9098-1231077e342f.png)
 
I just changed the rgb and depth intrinsics of the teddy calibration file using my kinect's parameters , and the remaining are unchanged like this
![image](https://user-images.githubusercontent.com/13608731/31979462-6f9ec0ba-b979-11e7-9e2a-b4efb64c901f.png)

I used the same calibration file when I runned the InfiniTAM using my kinect v1 directly and using the recorded sequences from the kinect... 
Maybe I also need to change the remaining parameters of the calibration file?

**Comment by AndreiBarsan** [comment]
Ah, you should try tuning the disparity calibration, i.e., the last two parameters. I'm not 100% sure that's what's causing the problem, but it looks like that to me.

Check out the 'readDisparityCalib' method (https://github.com/victorprad/InfiniTAM/blob/master/InfiniTAM/ITMLib/Objects/Camera/ITMCalibIO.cpp#L50) for more details on these parameters.

**Comment by ThePetrelLHY** [comment]
Oh! Thank you for your reply!
That solves my problem! I try to delete the last two parameters and let disparity calibration use the defalut values, and it works! 

Thank you very much!!!
