### ISSUE TITLE
Android and iOS not able to build

### ISSUE THREAD

**Issue by zaykl** [victorprad/InfiniTAM#86]
I build the system in my macbook success. But the code seems not able to build for Android and iOS. Like RelocLib is renamed FernRelocLib.

**Comment by sgolodetz** [comment]
I suspect the Android and iOS versions need updating in response to changes to the main code. I'll talk to @victorprad and see if I can fix it.

**Comment by omgware** [comment]
Anything new on iOS end? Still can't compile the project successfully.
I tried this sample project: www.robots.ox.ac.uk/~victor/infinitam/files/InfiniTAM_ios9.zip but it is very outdated now.

**Comment by sgolodetz** [comment]
@omgware I never got around to it unfortunately, sorry. I'm also now working somewhere else, so I'm unlikely to have time to look into it any more. I'll reassign the issue to @victorprad - maybe he or someone in his group has time to take a look.
