### ISSUE TITLE
Can not build ITMLib with CUDA 

### ISSUE THREAD

**Issue by dzmitrykomar** [victorprad/InfiniTAM#89]
Hello,

I try to build InfiniTAM in Windows 10 to use it with librealsense and it works fine if I build without CUDA, but as soon as I add CUDA in CMake, I cannot build ITMLib anymore. I get following error at ITMLib\ITMLib.dir\Debug\ITMLib.txt:

"  Building NVCC (Device) object ITMLib/CMakeFiles/ITMLib.dir/Debug/ITMLib_generated_CUDAInstantiations.cu.obj
  CMake Error at ITMLib_generated_CUDAInstantiations.cu.obj.Debug.cmake:222 (message):
    Error generating
    E:/install/infiniTAM/buildCUDA/ITMLib/CMakeFiles/ITMLib.dir//Debug/ITMLib_generated_CUDAInstantiations.cu.obj
   
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1."

I use VisualStudio Community 2017 v15.3.5 and CUDA Version 9.0.176.
Here are the added in CMake components:
![cmakeinfinitamcuda](https://user-images.githubusercontent.com/33931173/33174034-95685178-d056-11e7-8beb-9febe187de50.png)

Do you have an idea how can I get it to work?

**Comment by victorprad** [comment]
The current version of CUDA 9 only supports Visual Studio 2017 RTM. If need to generate a VS2015 project and install the required build tools.

**Comment by MicroYY** [comment]
I have the same problem. Did you solve it?

**Comment by dzmitrykomar** [comment]
I think I installed it without cuda at the end

MicroYY <notifications@github.com> schrieb am Do., 16. Mai 2019, 10:42:

**Comment by MicroYY** [comment]
Oh... Can it achieve real-time performance without GPU?

**Comment by dzmitrykomar** [comment]
Not really..

MicroYY <notifications@github.com> schrieb am Do., 16. Mai 2019, 11:31:

**Comment by sgolodetz** [comment]
For what it's worth, I'm using Visual Studio 2017 with CUDA 9.2, and it works fine if you install and use the v140 toolset (i.e. the Visual Studio 2015 build tools). See also `build-win.sh` on the `infinitam_v3.5` branch.

**Comment by MicroYY** [comment]
> For what it's worth, I'm using Visual Studio 2017 with CUDA 9.2, and it works fine if you install and use the v140 toolset (i.e. the Visual Studio 2015 build tools). See also `build-win.sh` on the `infinitam_v3.5` branch.

Oh, I switch to the v3.5  branch and it really works! Thanks !!!
