### ISSUE TITLE
how to handle duplicated vertices and degenerated triangle faces generated by Marching cubes in InfiniTAM?

### ISSUE THREAD

**Issue by charmland** [victorprad/InfiniTAM#91]
**_Observations_**:
mesh generated by Marching cubes in InfiniTAM contains many Duplicated Vertices and 
 a few Degenerated triangle faces. 

**Duplicated Vertices** 
   the content of  the mesh.obj file generated by InfiniTAM looks like:

> Vertex list=[v1 v2 v3 v4 v5 v6 ... ... ]
> Triangle index array=[ 0 1 2 3 4 5... ... ]

but when i open the file and check v4's coordinates,  i found that v4's coordinates are the same as v1;  and v5's coordinates are the same as v3.
     so the mesh.obj's content is essentially equal to:
> Vertex list=[p1 p2 p3 p1 p3 p4 ... ... ]
> Triangle index array=[ 0 1 2 3 4 5... ...]
   
where pi is the coordinate of corresponding vertex.

**Degenerated triangle faces** means that some triangle faces has two or more vertices with identical coordinates, resulting in a face degenerated to a line segment(two vertices' coordinates are identical) or a single point(all three vertices' coordinates are identical)

**_Question_**:
1. how to improve marching cubes algorithm to  prevent duplicate vertices?
2. how to prevent marching cubes from generating degenerated faces?
3. if there is no way to prevent degenerated faces, how to cope with mesh that contains degenerated faces?

**Comment by victorprad** [comment]
Our marching cubes algorithm was never really optimised, so it will indeed generate lots of duplicate vertices and faces. 

A standard duplication search in post processing (e.g. done by Meshlab on load) should be able to clear things out.

**Comment by charmland** [comment]
hi , victorprad, you're right. I've tried removing duplicate vertices using vcglib, but the resulting mesh  contains some degenerated faces,small cracks and non-manifold vertices and faces. I then fix it using vcglib again. Although vcglib can clean degenerated components in a mesh, I think the marching cubes algorithm can be improved using some ideas of [this paper](https://link.springer.com/article/10.1007%2Fs003710050112?LI=true) to prevent the degeneracy problem.
