### ISSUE TITLE
"w" :saving scene to model .  i can't use it.

### ISSUE THREAD

**Issue by 627633854** [victorprad/InfiniTAM#94]
/ORUtils/MemoryBlock.h(257) : cudaSafeCall() Runtime API error : out of memory.
how can i save a mesh model? what are  the steps?

**Comment by sgolodetz** [comment]
Have a look at line 103 of https://github.com/victorprad/InfiniTAM/blob/master/InfiniTAM/ITMLib/Core/ITMBasicEngine.tpp, which says:

    ITMMesh *mesh = new ITMMesh(settings->GetMemoryType());

At a guess, you're probably on a GPU which doesn't have enough memory to allocate a mesh of the default size. You can get around this by specifying a maximum number of triangles, as is done in SemanticPaint on lines 757-8 of https://github.com/torrvision/spaint/blob/scoreforest_grove/apps/spaintgui/Application.cpp:

    // Construct the mesh (specify a maximum number of triangles to avoid crash on the Titan Black).
    Mesh_Ptr mesh(new ITMMesh(settings->GetMemoryType(), 1 << 24));

If `1 << 24` is still too big, try something smaller.

**Comment by 627633854** [comment]
ok,i will try it .Thank you^_^！
