### ISSUE TITLE
The pose matrix and its inverse

### ISSUE THREAD

**Issue by wangarad** [victorprad/InfiniTAM#95]
First I want to say thank you for making this wonderful software!

This is not an issue, but rather a question concerning the pose matrix and its inverse;
- In the [`castRay()`](https://github.com/victorprad/InfiniTAM/blob/1f52e8c85df795cb7643977059b88c81e4a56e40/InfiniTAM/ITMLib/Engines/Visualisation/Shared/ITMVisualisationEngine_Shared.h#L102) method, [`pt_camera_f`](https://github.com/victorprad/InfiniTAM/blob/1f52e8c85df795cb7643977059b88c81e4a56e40/InfiniTAM/ITMLib/Engines/Visualisation/Shared/ITMVisualisationEngine_Shared.h#L114) represents pixel projected into camera space.
- As I understand, the point should be projected into world space and saved to [`pt_block_s`](https://github.com/victorprad/InfiniTAM/blob/1f52e8c85df795cb7643977059b88c81e4a56e40/InfiniTAM/ITMLib/Engines/Visualisation/Shared/ITMVisualisationEngine_Shared.h#L119).

I fail to understand why is the inverse of pose matrix (`invM`) used instead of the pose matrix:
`pt_block_s = TO_VECTOR3(`**`invM`**` * pt_camera_f) * oneOverVoxelSize;`

AFAIK `invM` = inverse of pose = extrinsic matrix = world-to-camera transform.
And pose matrix = camera-to-world transform.

What am I missing here?

**Comment by sgolodetz** [comment]
If I remember right, the InfiniTAM pose matrix is world-to-camera. So `invM` is the inverse of that, i.e. camera-to-world.

**Comment by wangarad** [comment]
Thank you for clearing this out, @sgolodetz , that makes perfect sense! I'm closing this issue.
